version: '2'
services:
  unit:
    image: golang:1.12
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    working_dir: /usr/src/myapp
    command: bash -c "pwd && go get -d -v && go test --cover -v ./... && go build -v -o test-repo"
